### ISSUE TITLE
Upcoming Changes

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#412]
# UPDATE (August, 2020)
Many of these issues are being tackled as I begin work on ScottPlot 4.1 (#505). \
I'll close this issue for now, and re-open / reassess it after 4.1 is released.

See the [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) for a larger-scale description of the current state and future goals of ScottPlot development.

## Task List (to be revisited after 4.1 is released)
- [ ] Make `Plottable` an interface (don't rename it though) and turn `visible` to `IsVisible()`
- [ ] Make `SignalDensity` and pull density-specific code out of `Signal` so `Signal` can stay simple and easy to extend or hack on. Will this affect `SignalConst`?
- [ ] See if we can use parallel by default, then delete the non-parallel methods from plottables (Scatter, Signal, and SignalConst) #419
- [ ] Create static methods to aid GetLimits code. It shouldn't have to be re-implemented discretely in every plottable.
- [ ] Create a central `Transform` module and have all plottables use its `GetPixel(x, y)` to convert data positions to screen pixels
- [ ] Add log support to `Transform`, magically adding log support to all plottables #207 #41 #29
- [ ] Add "show value under mouse" support #115 
- [ ] Add a text rendering method to `Drawing` and funnel all `Graphics.DrawString()` calls through it. Add alignment support, not just for text alignment but also for anchor alignment (aligned how, with reference to what?). Add arguments to Title, XLabel, and YLabel to control alignment of those labels #411
- [ ] Make grid a special type of plottable (`Renderable`?)
- [ ] Make labels (title, xlabel, ylabel) a special type of plottable (`Renderable`?)
- [ ] Make axes a special type of plottable (`Renderable`?)
- [ ] Support multiple Y axes #180, #213, #478
- [ ] Make legend a special type of plottable (`Renderable`?) so it's easier to customize #388 #318 #253 #45
- [ ] Don't use separate bitmaps for the figure, data, and legend. Instead use 1 bitmap and clipping to only draw on the desired component. This increases simplicity and performance.
- [ ] Make render system that accepts an existing Bitmap and renders onto it. Eventual goal is to not hold bitmaps in memory in ScottPlot. Ultimate goal is to remove system.drawing dependency.
- [ ] The render method should be really simple: Just iterate through a `List<Renderable>` and call the `Render()` method for each object (passing in the bitmap to render on).
- [ ] Make render system accept an `IRenderer` which defaults to a `System.Drawing` renderer, but will also accept a custom one (paving the way for a SkiaSharp+OpenGL control). Small-scale exploration of these concepts is explored on my [CsharpDataVis](https://swharden.com/CsharpDataVis/) page (under construction).
- [ ] Refactor legend ([#388](https://github.com/swharden/ScottPlot/issues/388)) to be a plottable (or some new type of plottable-like object). None of the user-facing methods will change. This will make it easier to implement different legends or let users create their own legends.
- [ ] Refactor markers ([#386](https://github.com/swharden/ScottPlot/pull/386)) to be classes instead of defined in an enum. Markers will implement `IMarker`, live in `ScottPlot.Markers`, markers have the ability to draw themselves. This makes it easy to switch between markers and even create custom markers that work for all plot types without modifying any ScottPlot code.
- [ ] Refactor axis and ticks to be their own plottables. This will do a better job to encapsulate tick code, and offer a means to create experimental tick systems ([#394](https://github.com/swharden/ScottPlot/issues/394)). It will also pave the way for multiple axis support such as dual-Y-axes ([#180](https://github.com/swharden/ScottPlot/issues/180)).
- [ ] Add a right-click menu to WpfPlot (like FormsPlot's)
- [ ] Create a Finance Demo (not a cookbook example, but a full demo program) to consolidate common finance-related tasks in one program. This demo should describe how to add live incoming data [#395](https://github.com/swharden/ScottPlot/issues/395), [#403](https://github.com/swharden/ScottPlot/issues/403)
- [ ] Chart control ([#358](https://github.com/swharden/ScottPlot/issues/358)) - `FormsChart` would be an alternative to `FormsPlot` which presents a chart-style interface more suitable for data logging applications.
- [ ] Finance Control - the general purpose chart control (`FormsPlot` and `WpfPlot`) have many features not suitable for finance charts, and vice-versa. A dedicated control for Candlestick / OHLC data could be really useful. Mouse interaction could be simplified for zooming around and reporting financial data under the mouse.
- [ ] Make plottable an `IPlottable`
- [ ] Rename all plottables (ouch): `PlottableSignal` -> `Plottable.Signal`
- [ ] Use design-time configurable properties (#455) instead of relying entirely on `Configure()`
- [ ] Turn `Tools` static class into a `Tools` namespace with smaller static classes
- [ ] make a much better financial plot demo #403 
- [ ] figure out how to implement better shared axes in user controls #399, #429
- [ ] create a benchmarking/testing app for the user controls that uses a timer to zoom and pan
- [ ] consider phasing-out user control Config() arguments in favor of properties you can edit in the GUI control property editor
- [ ] refactor internal messaging (between `Plot` methods and `Plottable` objects) to use style objects instead of long lists of arguments (originally discussed in #415, thanks @StendProg)
- [ ] make it easier to reset the plot by creating `Plot.Reset()` (#407)
- [ ] create a way to add bitmaps to the plot or figure. Make it possible to use a bitmap as an axis label (#446)
- [ ] modify website to add warning when viewing old cookbooks (#435)
- [ ] add "view source code" button to all demos (#434)
- [ ] add _show value on hover_ (or _show value on click_) to the user control right-click menu (#465)
- [ ] refactor how mouse hover works to allow "show value under cursor" or "show trace under cursor" (#471)
- [ ] heatmaps (#420, #441, #458, #424, #482, #457) and vector fields (#438, #439) are mostly done but need finishing

**Comment by swharden** [comment]
Many of these issues are being tackled as I begin work on ScottPlot 4.1 (#505). \
I'll close this issue for now, and re-open / reassess it after 4.1 is released.

See the [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) for a larger-scale description of the current state and future goals of ScottPlot development.
