### ISSUE TITLE
Checklist for more heatmap features

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#457]
**What can we do to make ScottPlot better?**
- [x] Allow user-set intensity scale
- [x] Transparent heatmaps w/ background image
    - [ ] Scaling options? Are these necessary?
    - [ ] ~~Nullables in intensities map to transparent?~~ I don't like this idea
    - [x] Map intensities below threshold to transparent
    - [x] It will be valuable to support transparent image above heatmap as well as transparent heatmap above image
        - [x] For example geographic heatmaps
- [ ] Better axes
- [x] More colourmaps
    - [x] cmocean
    - [ ] ~~plotly~~ doesn't look promising
    - [x] custom
- [x] `ScottPlot.Tools.XYToIntensities()`
    - [x] Gaussian and density-based
- [ ] Strange rounding? #482

**Comment by Benny121221** [comment]
Transparent heatmaps example:

https://github.com/swharden/ScottPlot/pull/424#issuecomment-642446925

**Comment by swharden** [comment]
What do you think about calculating the heatmap from input data? 

On one hand this feels like scope creep, but on the other hand a core goal of ScottPlot is to make visualizing `double[] xs` and `double[] ys` easy so maybe this isn't too far out. 🤔 

data input | heatmap output
---|---
![image](https://user-images.githubusercontent.com/4165489/84423621-bb3a1980-abec-11ea-9fdd-c8f5ab859df6.png) | ![image](https://user-images.githubusercontent.com/4165489/84423634-c12ffa80-abec-11ea-954d-ae092443d1d7.png)

**Comment by Benny121221** [comment]
It doesn't seem difficult but I don't see the use case for it. I assume there is a use case, but if its only applicable to a niche audience, that audience would probably be better served had they implemented it themselves

**Comment by swharden** [comment]
I'll preface this by saying you're probably light, and according to the YAGNI principle we should wait until the need actually arises before implementing this...

...but a use case I could envision is when you have a massively large number of X/Y data points. A traditional scatter plot would look like an opaque blob. Being able to create a heatmap from that X/Y data is a way to present it in a way you can visualize hotspots in the data.

**Comment by Benny121221** [comment]
Oh, I see, I misunderstood input data, I thought that meant mouseclicks. I don't mind the idea, I think it would be best implemented as a `ScottPlot.Tools.XYToIntensities()` sorta thing.

It would in principle be most correct to express the intensities as the density of points within a circle of radius r, however it would be easier to use squares/rectangles. Plus, when using circles you won't have a meaningful scale, as circles will necessarily count points twice (or not at all), whereas squares can tile the whole thing, counting each point exactly once.

Plus, density is a derived quantity of metre^2 or metre^3, normally expressed in counts/square metre.

**Comment by swharden** [comment]
I think a common way to do this is for each heatmap pixel (or tile) to represent the sum of all points where each is Gaussian-weighted according to its distance. Adjusting the steepness of the Gaussian curve (sigma) appears as "smoothing" of the heatmap.

A shortcut is just to bin all data into the heatmap tiles, then gaussian weight each tile by its neighbors. It looks like there are several options here 🤔 

![image](https://user-images.githubusercontent.com/4165489/84429982-09541a80-abf7-11ea-918f-481c92ca69f0.png)

**Comment by Benny121221** [comment]
I had thought about this way, I was thinking of using the reciprocals of the distance to each point, but a gaussian filter would be more forgiving and better customizable (not to mention well defined for distances of 0)

I think a gaussian filter creates better-looking results for most situations, but it does have the disadvantage that the scale becomes meaningless. I think we should probably support both gaussian and density varieties

**Comment by Benny121221** [comment]
I'm working on this in https://github.com/Benny121221/ScottPlot/tree/heatmap-improvements but I'm not going to open a PR just yet

**Comment by olofszymczak** [comment]
@Benny121221 you mentioned that you didn't think the idea of adjusting the radius size is a good idea. It gives you the ability to manipulate the data in a standard way. If you cant adjust the size of the radius you have to some how add more data points which may not be possible.

![image](https://user-images.githubusercontent.com/16024904/84451882-a1a1dc00-ac97-11ea-9ab8-9d5df5bcec8a.png)

Increase intensity
![image](https://user-images.githubusercontent.com/16024904/84451916-b41c1580-ac97-11ea-8a16-d31cf0889cae.png)

Increase Radius
![image](https://user-images.githubusercontent.com/16024904/84451961-d9a91f00-ac97-11ea-8cae-ffce8c564e52.png)

**Comment by Benny121221** [comment]
@olofszymczak I was confused by the radius property, but it comes from converting XY data to a heatmap. This functionality is given by `ScottPlot.Tools.XYToIntensity`: https://github.com/swharden/ScottPlot/blob/6e3716946fe59dc1a69c94e02d09558251c25d61/src/ScottPlot/Tools.cs#L332-L395

The `sampleWidth` parameter (I really don't like the name) does the same thing as increasing the radius, however it's not a radius as it doesn't use circles. Depending on which mode you call the method with it is either a standard deviation or the sidelength of a square. Squares are best for when the units are relevant because no points are counted twice (or not at all), and densities are given in terms of counts/square area.

The gaussian mode is best for most other things, it looks the best and is very good at showing clusters of points. It looks like your example might be giving a gaussian (or similar function) and misnaming the parameter as a radius, considering the smooth edges. If the parameter were a radius it would look like the density mode but with circles instead of squares.

**Comment by swharden** [comment]
There hasn't been movement here in a few months so I'll close this issue. The current status of heatmaps is they are partially supported, `Plot.PlotHeatmap()` is pubic but marked obsolete. Some heatmap-related interactive logic snaked its way into the user control code, but that will likely get refactored-out if the control logic is isolated in its own module (#496) so I'll keep things simple and leave all the current functionality the same. This issue can be re-opened if work/progress on this front resumes
