### ISSUE TITLE
Refactor entire rendering system to use IRenderable

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#516]
**Goal:** Refactor _renderable_ plot items (anything that's not plotted on the coordinate space) into single modules which implement `IRenderable` (#511) that store configuration and rendering code in the same class. 
- [x] Figure background (#511)
- [x]  Data background (#511)
- [x]  Grid lines (#511)
- [x]  Benchmark (#511)
- [x]  Legend (#515, #517)
- [ ] Refactor the coordinate system (#518)
- [ ]  Refactor the layout system (#513)
- [ ]  Ticks and tick labels (#514)
- [ ]  Axis labels and title (#513)

These non-breaking changes should occur prior to the breaking changes introduced by ScottPlot 4.1 (#505, #506).

**Motivation:** Examples of tasks which are currently hard but will become easy after this refactor include alternative tick calculations (#394, #456), second Y axis (#180, #213, #478, #510), and placement customization of above-plot annotations (#321) and legends (#388).

**Comment by swharden** [comment]
Excellent progress has been made on this front (#519). Work will continue in #521
